spring.application.name=Demo_employee
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/employee
spring.datasource.username=root
spring.datasource.password=Vimal@#7534

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update


# JWT Configuration
jwt.secret=MySecretKeyMySecretKeyMySecretKeyMySecretKey12345
jwt.expiration=3600000